export enum Expertise {
  OTHER = 'OTHER',
  SOCIAL = 'SOCIAL',
  INFANT = 'INFANT',
  CLINICAL = 'CLINICAL',
  JURIDICAL = 'JURIDICAL',
  EDUCATIONAL = 'EDUCATIONAL',
  ORGANIZATIONAL = 'ORGANIZATIONAL',
  PSYCHOTHERAPIST = 'PSYCHOTHERAPIST',
  NEUROPSYCHOLOGY = 'NEUROPSYCHOLOGY',
}
